rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('areachart/', views.areachart, name='areachart'),
    path('donutchart/', views.donutchart, name='donutchart'),
    path('barchart/', views.barchart, name='barchart'),
    path('mixedchart/', views.mixedchart, name='mixedchart'),
    path('table/', views.table, name='table'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from rango import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.contrib.auth.models import User


class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import UserProfile


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from django.shortcuts import render
from django.utils import timezone
from django.shortcuts import redirect
from django.urls import reverse
from rango.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required


def index(request):
    # Construct a dictionary to pass to the template engine as its context.
    # Note the key boldmessage is the same as {{ boldmessage }} in he template!
    context_dict = {}
    context_dict = {'boldmessage':
                    'Crunchy, creamy, cookie, candy, cupcake!'}

    # Return a rendered responde to send to the client.
    # We make use of the shortcut function to make our lives easier.
    # Note that the first parameter is the template we wish to use.
    return render(request, 'rango/index.html', context=context_dict)


def areachart(request):
    return render(request, 'rango/areachart.html')

def donutchart(request):
    return render(request, 'rango/donutchart.html')

def barchart(request):
    return render(request, 'rango/barchart.html')

def mixedchart(request):
    return render(request, 'rango/mixedchart.html')

def table(request):
    return render(request, 'rango/table.html')


def register(request):
    # A boolean value for telling the template
    # whether the registration was successful.
    # Set to False initially. Code changes value to
    # True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()
            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves,
            # we set commit=False. This delays saving the model
            # until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and
            # put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to indicate that the template
            # registration was successful.
            registered = True
        else:
            # Invalid form or forms - mistakes or something else?
            # Print problems to the terminal.
            print(user_form.errors, profile_form.errors)
    else:
        # Not a HTTP POST, so we render our form using two ModelForm instances.
        # These forms will be blank, ready for user input.
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render(request,
                  'rango/register.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
        # We use request.POST.get('<variable>') as opposed
        # to request.POST['<variable>'], because the
        # request.POST.get('<variable>') returns None if the
        # value does not exist, while request.POST['<variable>']
        # will raise a KeyError exception.
        username = request.POST.get('username')
        password = request.POST.get('password')
        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)
        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value),
        # no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your Rango account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied.")
    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'rango/login.html')


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')


# Use the login_required() decorator to ensure only those logged in can
# access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    # Take the user back to the homepage.
    return redirect(reverse('rango:index'))

templates/rango/areachart.html
{% extends 'rango/base.html' %}
{% load staticfiles %}


{% block title_block %}
Area Chart
{% endblock %}

{% block body_block %}
<!-- Area Chart -->
<div class="col-xl-8 col-lg-7">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Area Chart</h6>
    </div>
    <div class="card-body">
      <div class="chart-area">
        <canvas id="myAreaChart"></canvas>
      </div>
      <hr>
      El estilo está en el archivo
      <code>/static/js/chart-area.js</code>.
    </div>
  </div>
</div>


{% endblock %}

templates/rango/barchart.html
{% extends 'rango/base.html' %}
{% load staticfiles %}


{% block title_block %}
Bar Chart
{% endblock %}

{% block body_block %}

<!-- Bar Chart -->
<div class="col-xl-8 col-lg-7">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Bar Chart</h6>
    </div>
    <div class="card-body">
      <div class="chart-bar">
        <canvas id="myBarChart"></canvas>
      </div>
      <hr>
      El estilo del Bar Chart está en el archivo
      <code>/static/js/char-bar.js</code>.
    </div>
  </div>
</div>

<div class="col-xl-8 col-lg-7">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Bar Chart</h6>
    </div>
    <div class="card-body">
      <div class="chart-bar">
        <canvas id="myHorizontalChart"></canvas>
      </div>
      <hr>
      El estilo del Bar Chart está en el archivo
      <code>/static/js/char-bar.js</code>.
    </div>
  </div>
</div>

<div class="col-xl-8 col-lg-7">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Bar Chart</h6>
    </div>
    <div class="card-body">
      <div class="chart-bar">
        <canvas id="myBarGroupChart"></canvas>
      </div>
      <hr>
      El estilo del Bar Chart está en el archivo
      <code>/static/js/char-bar.js</code>.
    </div>
  </div>
</div>



{% endblock %}

templates/rango/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">

<!-- HEAD CON LA INFO DE LA PAGINA -->

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <!-- Icono de la pagina -->
  <link rel="icon" href="{% static 'images/favicon.ico' %}">
  <title>
    Dashboards - {% block title_block %} {% endblock %}
  </title>
  <link href="../../static/css/estilo.css" rel="stylesheet">
  <!-- Añadimos Bootstrap core CSS -->
  <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <!-- Añadimos el dashboard -->
  <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
</head>


<!-- CUERPO DE LA PAGINA -->

<body>
  <header>
    <!-- BARRA DE NAVEGACION DE ARRIBA -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
      <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:logout' %}?next=/rango/">Logout</a></li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:register' %}">Register Here</a></li>
          <li class="nav-item ">

            <a class="nav-link" href="{% url 'rango:login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>


  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">

        <!-- CONTENIDO DE LA IZQUERDA -->
        <div class="sidebar-sticky">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:areachart' %}">Area Chart</a></li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:donutchart' %}">Donut Chart</a></li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:barchart' %}">Bar Chart</a></li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'rango:mixedchart' %}">Mixed Chart</a></li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:table' %}"> Tabla de datos</a></li>
        </div>
      </nav>
      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

        <!-- AQUI VA EL CONTENIDO DE CADA PAGINA -->
        {% block body_block %}

        {% endblock %}


        <!-- FOOTER -->
        <footer>
          <p>Aquí va el footer</p>
        </footer>
      </main>
    </div>
  </div>
  <!-- Bootstrap core JavaScript -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script>
    window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')
  </script>
  <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js">
  </script>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
  <script src="../../static/js/char-area.js"></script>
  <script src="../../static/js/char-bar.js"></script>
  <script src="../../static/js/char-pie.js"></script>
  <script src="../../static/js/char-mixed.js"></script>

  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>
  <script src="../../static/js/database.js"></script>
</body>

</html>

templates/rango/donutchart.html
{% extends 'rango/base.html' %}
{% load staticfiles %}


{% block title_block %}
Donut Chart
{% endblock %}


{% block body_block %}
<div class="col-xl-4 col-lg-5">
  <div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Donut Chart</h6>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      <div class="chart-pie pt-4">
        <canvas id="myDonutChart"></canvas>
      </div>
      <hr>
      El estilo del Donut Chart está en el archivo
      <code>/static/js/char-pie.js</code>.
    </div>
  </div>
</div>

<div class="col-xl-4 col-lg-5">
  <div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Pie Chart</h6>
    </div>
    <!-- Card Body -->
    <div class="card-body">
      <div class="chart-pie pt-4">
        <canvas id="myPieChart"></canvas>
      </div>
      <hr>
      El estilo del Donut Chart está en el archivo
      <code>/static/js/char-pie.js</code>.
    </div>
  </div>
</div>
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Index
{% endblock %}

{% block body_block %}
<!-- Begin Page Content -->
<div class="container-fluid">

  <!-- Page Heading -->
  <h1 class="h3 mb-2 text-gray-800">Charts</h1>
  <p class="mb-4">Aqui podemos observar el dashboard completo</p>

  <!-- Content Row -->
  <div class="row">

    <div class="col-xl-8 col-lg-7">

      <!-- Area Chart -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Area Chart</h6>
        </div>
        <div class="card-body">
          <div class="chart-area">
            <canvas id="myAreaChart"></canvas>
          </div>
          <hr>

        </div>
      </div>

      <!-- Bar Chart -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Bar Chart</h6>
        </div>
        <div class="card-body">
          <div class="chart-bar">
            <canvas id="myBarChart"></canvas>
          </div>

          <hr>
          Aquí podemos poner texto
        </div>
      </div>

    </div>

    <!-- Donut Chart -->
    <div class="col-xl-4 col-lg-5">
      <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Donut Chart</h6>
        </div>
        <!-- Card Body -->
        <div class="card-body">
          <div class="chart-pie pt-4">
            <canvas id="myPieChart"></canvas>
          </div>
          <hr>

        </div>
      </div>
    </div>
  </div>

</div>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Login
{% endblock %}

{% block body_block %}
<link href="https://getbootstrap.com/docs/4.0/examples/signin/signin.css" rel="stylesheet">
<div class="jumbotron p-4">
  <h1 class="jumbotron-heading">Login</h1>
</div>
<div class="container">
  <form class="form-signin" role="form" method="post" action=".">
    {% csrf_token %}
    <label for="inputUsername" class="sr-only">Username</label>
    <input type="text" name="username" id="id_username" class="form-control" placeholder="Username" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" name="password" id="id_password" class="form-control" placeholder="Password" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Submit">Sign in</button>
  </form>
</div>
{% endblock %}

templates/rango/mixedchart.html
{% extends 'rango/base.html' %}
{% load staticfiles %}


{% block title_block %}
Mixed Chart
{% endblock %}

{% block body_block %}
<!-- Mixed Chart -->
<div class="col-xl-8 col-lg-7">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Mixed Chart</h6>
    </div>
    <div class="card-body">
      <div class="chart-area">
        <canvas id="myMixedChart"></canvas>
      </div>
      <hr>
      El estilo está en el archivo
      <code>/static/js/chart-mixed.js</code>.
    </div>
  </div>
</div>


{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Register
{% endblock %}

{% block body_block %}
<h1>Register for Rango</h1>
{% if registered %}
Rango says: <strong>thank you for registering!</strong>
<a href="{% url 'rango:index' %}">Return to the homepage.</a><br />

{% else %}
Rango says: <strong>register here!</strong><br />
<div class="container">
  <div class="row">
    <div class="form-group">
      <form role="form" method="post" action=".">
        {% csrf_token %}
        <div class="form-group">
          <p class="required"><label class="required" for="id_username">
              Username:</label>
            <input class="form-control" id="id_username" maxlength="30" name="username" type="text" />
            <span class="helptext">
              Required. 30 characters or fewer.
              Letters, digits and @/./+/-/_ only.
            </span>
          </p>
          <p class="required"><label class="required" for="id_email">
              E-mail:</label>
            <input class="form-control" id="id_email" name="email" type="email" />
          </p>
          <p class="required"><label class="required" for="id_password1">
              Password:</label>
            <input class="form-control" id="id_password1" name="password1" type="password" />
          </p>
          <p class="required">
            <label class="required" for="id_password2">
              Password confirmation:</label>
            <input class="form-control" id="id_password2" name="password2" type="password" />
            <span class="helptext">
              Enter the same password as before, for verification.
            </span>
          </p>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}